version: '3'

services:
    web:
        container_name: Programmerstasken_web
        build:
            context: .
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
